### ISSUE TITLE
How to get mix task exceptions to work?

### ISSUE THREAD

**Issue by Zeneixe** [jarednorman/plugsnag#17]
Hi, I'm loving this project, thanks a lot!

We have some big tasks (running via Heroku scheduler) that we would like to track in bugsnag, still on a phoenix app

We tried this test exception task but couldn't get it to work

```
defmodule Mix.Tasks.Carwow.TestException do
  def run(_args) do
    {:ok, _started} = Application.ensure_all_started(:carwow_api, :permanent)
    try do
      raise "Test Exception"
    rescue
      e -> Bugsnag.report(e)
    end
  end
end
```

**Comment by Zeneixe** [comment]
This will be fixed when this PR will be merged:

https://github.com/jarednorman/bugsnag-elixir/pull/35

**Comment by Zeneixe** [comment]
Can you bump the dependency of bugsnag-elixir to version:

1.4.0-beta1 ?

**Comment by mootpointer** [comment]
At the moment I'd prefer not to – there's no strict dependency relationship between the two versions.

I'd suggest adding `{:bugsnag, "~> 1.4.0-beta1", override: true}` to your mixfile.

**Comment by mootpointer** [comment]
Additionally I'm going to close this issue as it pertains to `bugsnag-elixir` and not `plugsnag`.
