### ISSUE TITLE
Configuration option to report to Bugsnag based on Mix.env 

### ISSUE THREAD

**Issue by ashwini709** [jarednorman/plugsnag#18]
Neither of the following stops plugsnag from reporting the errors to Bugsnag while working on other environments (development, staging)

`config :bugsnag, use_logger: Mix.env == :prod`
`config :plugsnag, use_logger: Mix.env == :prod` -> if this exist

What is the way to control reporting errors based on environment?

**Comment by ashwini709** [comment]
Can always do the following using the custom error report option,

```
  def build_error_report(error_report, conn) do
    if Application.get_env(:bugsnag, :use_logger) do
      Plugsnag.BasicErrorReportBuilder.build_error_report(error_report, conn)
    end
  end
```

Thanks

**Comment by mootpointer** [comment]
Sorry, I've been a bit busy with some other things. There is a way, but I'm pretty sure this isn't what you're looking for.

From my recollection `use_logger` is about using the `sasl` logger to catch supervised crashes.

**Comment by ashwini709** [comment]
When we `use Plugsnag` in the router, there is no configuration control to report the errors/exceptions to Bugsnag only when the environment is prod, or some condition defined by us.

**Comment by mootpointer** [comment]
Resolved upstream in the Bugsnag package in version 1.5.0. Thanks for your help.

**Comment by aizotov** [comment]
What's the solution here? It's not clear, from the documentation, how to disable plugsnag in dev and test environments.
