### ISSUE TITLE
Dialyzer errors under erlang 25.1 (but not 25.0)

### ISSUE THREAD

**Issue by PaulOstazeski** [jarednorman/plugsnag#47]
When upgrading a project using plugsnag from erlang 25.0 to erlang 25.1, the following error was generated:

```
Unknown warning:
:callback_not_exported


Legacy warning:
lib/plugsnag.ex:3: Callback function handle_errors/2 exists but is not exported (behaviour 'Elixir.Plug.ErrorHandler')
________________________________________________________________________________
```

**Comment by ceolinrenato** [comment]
I think it could be fixed by making the function public

https://github.com/bugsnag-elixir/plugsnag/pull/48

**Comment by PaulOstazeski** [comment]
I tried that, and while I may be missing something, it did not change the end result. Same dialyzer error in the parent project.

**Comment by PaulOstazeski** [comment]
Oddly, it does **not** happen when I run `mix dialyzer` in _this_ codebase with the same versions of erlang 25.1 and elixir 1.13.1-otp-25

**Comment by ceolinrenato** [comment]
> Oddly, it does **not** happen when I run `mix dialyzer` in _this_ codebase with the same versions of erlang 25.1 and elixir 1.13.1-otp-25

Maybe PLT was cached. Making the function public worked for me on 1.14 and erlang 25.1
