### ISSUE TITLE
All exceptions show up under the production release stage

### ISSUE THREAD

**Issue by fbjork** [jarednorman/plugsnag#7]
All exceptions show up as "production" in Bugsnag. Any idea why this is happening? I'm setting MIX_ENV=staging, but it still shows up as production.

**Comment by jarednorman** [comment]
Even in development?

**Comment by fbjork** [comment]
Yes, in development too. This is a Phoenix framework app btw. Let me know if I can share anything else that might help.

**Comment by jarednorman** [comment]
You're using the latest version?

Edit: The only version that supports the `MIX_ENV` as the release stage is the master. I haven't rolled a release that includes that yet.

**Comment by fbjork** [comment]
Using version 1.0.1. Any ETA on the next release?

**Comment by fbjork** [comment]
@jarednorman Just pushed up this PR: https://github.com/jarednorman/plugsnag/pull/8 perhaps you could cut a new release once it's merged?
